Repository woowa-techcamp-2020/bmart-6, pull requests merged in 2020-08, with the labels that each got.

#6 Sequelize 활용하여 API 구현(Product, User, Category, Subcategory)
  .gitignore
  server/.env.example
  server/app.js
  server/bin/www
  server/controllers/category.js
  server/controllers/product.js
  server/controllers/subcategory.js
  server/controllers/user.js
  server/models/category.js
  server/models/index.js
  server/models/order.js
  server/models/order_product_relation.js
  server/models/product.js
  server/models/subcategory.js
  server/models/user.js
  server/models/user_product_relation.js
  server/package-lock.json
  server/package.json
  server/routes/category.js
  server/routes/index.js
  server/routes/product.js
  server/routes/subcategory.js
  server/routes/user.js
Labels: feature, 백엔드

#9 백엔드 로그인, 회원가입 API > Passport + JWT 추가
  .prettierrc.js
  server/.env.example
  server/app.js
  server/bin/www
  server/controllers/category.js
  server/controllers/product.js
  server/controllers/subcategory.js
  server/controllers/user.js
  server/lib/passport.js
  server/middlewares/auth.js
  server/middlewares/error.js
  server/middlewares/validator.js
  server/models/category.js
  server/models/index.js
  server/models/order.js
  server/models/order_product_relation.js
  server/models/product.js
  server/models/subcategory.js
  server/models/user.js
  server/models/user_product_relation.js
  server/package-lock.json
  server/package.json
  server/routes/category.js
  server/routes/index.js
  server/routes/product.js
  server/routes/subcategory.js
  server/routes/user.js
  server/utils/salt.js
  server/yarn.lock
Labels: feature, 백엔드

#17 백엔드 API 설계 및 AWS Ec2에 web server, db server 설치
  server/controllers/banner.js
  server/controllers/category.js
  server/controllers/order.js
  server/controllers/product.js
  server/controllers/subcategory.js
  server/controllers/user.js
  server/middlewares/error.js
  server/middlewares/validator.js
  server/models/banner.js
  server/models/index.js
  server/models/order.js
  server/models/order_product_relation.js
  server/models/product.js
  server/package.json
  server/routes/banner.js
  server/routes/category.js
  server/routes/index.js
  server/routes/order.js
  server/routes/product.js
  server/routes/subcategory.js
  server/routes/user.js
  server/utils/constants.js
Labels: feature, 백엔드, 환경설정

#15 UseProduct(Custom Hook), routing, subCategoryPage 기능 구현
  .gitignore
  client/.gitignore
  client/README.md
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.tsx
  client/src/apis/index.tsx
  client/src/apis/product.tsx
  client/src/commons/constants/strings.ts
  client/src/components/ProductCard/index.tsx
  client/src/components/ProductCard/style.ts
  client/src/components/ProductCardGrid/index.tsx
  client/src/components/ProductCardGrid/style.ts
  client/src/components/ProductCardGridHeader/index.tsx
  client/src/components/ProductCardGridHeader/style.ts
  client/src/hooks/useApiRequests.tsx
  client/src/hooks/useProducts/actions.ts
  client/src/hooks/useProducts/index.ts
  client/src/hooks/useProducts/reducer.ts
  client/src/hooks/useProducts/types.ts
  client/src/index.css
  client/src/index.tsx
  client/src/libs/axios.ts
  client/src/pages/Subcategory/index.tsx
  client/src/react-app-env.d.ts
  client/src/setupTests.ts
  client/src/templates/Default/index.tsx
  client/src/templates/Default/style.ts
  client/src/templates/Subcategory/index.tsx
  client/src/templates/Subcategory/style.ts
  client/src/types/Actions.tsx
  client/src/types/Data.tsx
  client/src/types/States.tsx
  client/tsconfig.json
  client/yarn.lock
  server/app.js
  server/models/product.js
  server/package.json
  server/yarn.lock
Labels: feature, study, 백엔드, 프론트엔드

#22 템플릿 폴더 삭제 및 types 파일들 확장자 변경
  client/src/templates/Subcategory/index.tsx
  client/src/templates/Subcategory/style.ts
  client/src/types/actions.ts
  client/src/types/data.ts
  client/src/types/states.ts
Labels: 프론트엔드

#23 크롤링 후 데이터 맵핑, 자동 데이터 추가 코드 구현
  server/.env.example
  server/app.js
  server/models/index.js
  server/seeder/data/category.json
  server/seeder/data/product.json
  server/seeder/data/subcategory.json
  server/seeder/index.js
  server/seeder/raw_data/1.json
  server/seeder/raw_data/10.json
  server/seeder/raw_data/11.json
  server/seeder/raw_data/12.json
  server/seeder/raw_data/13.json
  server/seeder/raw_data/14.json
  server/seeder/raw_data/15.json
  server/seeder/raw_data/16.json
  server/seeder/raw_data/17.json
  server/seeder/raw_data/18.json
  server/seeder/raw_data/19.json
  server/seeder/raw_data/2.json
  server/seeder/raw_data/20.json
  server/seeder/raw_data/21.json
  server/seeder/raw_data/22.json
  server/seeder/raw_data/23.json
  server/seeder/raw_data/24.json
  server/seeder/raw_data/25.json
  server/seeder/raw_data/26.json
  server/seeder/raw_data/27.json
  server/seeder/raw_data/3.json
  server/seeder/raw_data/4.json
  server/seeder/raw_data/5.json
  server/seeder/raw_data/6.json
  server/seeder/raw_data/7.json
  server/seeder/raw_data/8.json
  server/seeder/raw_data/9.json
Labels: feature, 백엔드, 환경설정

#29 배너 슬라이더 구현
  client/src/App.tsx
  client/src/commons/constants.ts
  client/src/components/BannerSlider/Indicator/index.tsx
  client/src/components/BannerSlider/Indicator/style.ts
  client/src/components/BannerSlider/index.tsx
  client/src/components/BannerSlider/style.ts
  client/src/pages/BannerPage/index.tsx
  client/src/pages/BannerPage/style.ts
  client/src/types/data.ts
Labels: feature, 프론트엔드

#28 상품 Sort Modal, Grid Header UI 및 기능 구현
  client/package.json
  client/src/App.tsx
  client/src/commons/constants.ts
  client/src/components/ProductCard/index.tsx
  client/src/components/ProductCardGrid/style.ts
  client/src/components/ProductCardGridHeader/index.tsx
  client/src/components/ProductCardGridHeader/style.ts
  client/src/components/SortModal/index.tsx
  client/src/components/SortModal/style.ts
  client/src/pages/SubcategoryPage/index.tsx
  client/src/styles/globalstyle.scss
  client/src/styles/reactModal.scss
  client/src/types/data.ts
  client/yarn.lock
  server/models/product.js
Labels: feature, 백엔드, 프론트엔드

#32 프론트엔드 구조 재구성(small, medium, large)
  client/src/components/index.ts
  client/src/components/large/BestSellerSection/index.tsx
  client/src/components/large/CategoryProductSection/index.tsx
  client/src/components/large/EatNowSection/index.tsx
  client/src/components/large/ForYouSection/index.tsx
  client/src/components/large/HotDealSection/index.tsx
  client/src/components/large/PageHeader/index.tsx
  client/src/components/medium/BannerSlider/index.tsx
  client/src/components/medium/BannerSlider/style.ts
  client/src/components/medium/CategoryIconGrid/index.tsx
  client/src/components/medium/ProductCardGrid/index.tsx
  client/src/components/medium/ProductCardGrid/style.ts
  client/src/components/medium/ProductCardGridHeader/index.tsx
  client/src/components/medium/ProductCardGridHeader/style.ts
  client/src/components/medium/ProductCardListView/index.tsx
  client/src/components/medium/ProductCardListView/style.ts
  client/src/components/medium/ProductSortModal/index.tsx
  client/src/components/medium/ProductSortModal/style.ts
  client/src/components/small/BannerIndicator/index.tsx
  client/src/components/small/BannerIndicator/style.ts
  client/src/components/small/ProductCard/index.tsx
  client/src/components/small/ProductCard/style.ts
  client/src/components/small/SectionDivider/index.tsx
  client/src/pages/BannerPage/index.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/SubcategoryPage/index.tsx
Labels: 프론트엔드, 환경설정

#26 프론트엔드 로그인/회원가입 구현
  .gitignore
  client/package.json
  client/src/App.tsx
  client/src/apis/category.tsx
  client/src/apis/index.ts
  client/src/apis/user.tsx
  client/src/commons/constants.ts
  client/src/components/index.ts
  client/src/components/large/JoinSection/index.tsx
  client/src/components/large/JoinSection/style.ts
  client/src/components/large/LoginSection/index.tsx
  client/src/components/large/LoginSection/style.ts
  client/src/components/small/SectionHeader/index.tsx
  client/src/components/small/UserFooter/index.tsx
  client/src/components/small/UserFooter/style.ts
  client/src/components/small/UserHeader/index.tsx
  client/src/components/small/UserHeader/style.ts
  client/src/components/small/UserInput/index.tsx
  client/src/components/small/UserInput/style.ts
  client/src/components/small/UserTitle/index.tsx
  client/src/components/small/UserTitle/style.ts
  client/src/contexts/user/actions.ts
  client/src/contexts/user/index.tsx
  client/src/contexts/user/reducer.ts
  client/src/index.tsx
  client/src/libs/axios.ts
  client/src/pages/UserPage/index.tsx
  client/src/pages/index.ts
  client/src/types/data.ts
  client/src/types/states.ts
  client/src/utils/storage.ts
  client/src/utils/validation.ts
  client/tsconfig.json
  client/yarn.lock
  server/bin/www
Labels: feature, 프론트엔드

#35 MainPage 및 ProductCategorySection 스크롤 반응형 구현
  client/public/assets/bmart-logo.png
  client/public/assets/category-1.png
  client/public/assets/category-10.png
  client/public/assets/category-2.png
  client/public/assets/category-3.png
  client/public/assets/category-4.png
  client/public/assets/category-5.png
  client/public/assets/category-6.png
  client/public/assets/category-7.png
  client/public/assets/category-8.png
  client/public/assets/category-9.png
  client/public/assets/main-bmart.png
  client/public/assets/main-bread.png
  client/public/assets/main-choco.png
  client/public/assets/main-egg.png
  client/public/assets/main-hair.png
  client/public/assets/main-ice.png
  client/public/assets/main-mealkit.png
  client/public/assets/main-milk.png
  client/public/assets/main-salad.png
  client/public/assets/main-yasik.png
  client/src/App.tsx
  client/src/commons/constants.ts
  client/src/commons/svgs.tsx
  client/src/components/index.ts
  client/src/components/large/BestSellerSection/index.tsx
  client/src/components/large/CategoryProductSection/index.tsx
  client/src/components/large/CategoryProductSection/style.ts
  client/src/components/large/EatNowSection/index.tsx
  client/src/components/large/ForYouSection/index.tsx
  client/src/components/large/PageHeader/index.tsx
  client/src/components/large/ProductSection/index.tsx
  client/src/components/large/ProductSection/style.ts
  client/src/components/medium/CategoryIconGrid/index.tsx
  client/src/components/medium/CategoryIconGrid/style.ts
  client/src/components/medium/CategoryProductHeader/index.tsx
  client/src/components/medium/CategoryProductHeader/style.ts
  client/src/components/medium/PageHeader/index.tsx
  client/src/components/medium/PageHeader/style.ts
  client/src/components/medium/ProductCardGrid/style.ts
  client/src/components/medium/SectionHeader/index.tsx
  client/src/components/medium/SectionHeader/style.ts
  client/src/components/small/Framework7Icon/index.tsx
  client/src/components/small/SectionDivider/index.tsx
  client/src/pages/BannerPage/index.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/index.ts
  client/src/styles/globalstyle.scss
  client/src/types/data.ts
Labels: feature, 프론트엔드

#38 Subcategory page 라우팅 구현
  client/src/App.tsx
  client/src/components/large/CategoryProductSection/index.tsx
  client/src/components/medium/CategoryIconGrid/index.tsx
  client/src/components/medium/CategoryProductHeader/index.tsx
  client/src/components/medium/PageHeader/index.tsx
  client/src/components/medium/PageHeader/style.ts
  client/src/components/medium/ProductCardGridHeader/index.tsx
  client/src/pages/SubcategoryPage/index.tsx
Labels: feature, 프론트엔드

#39 메인 페이지 핫딜 섹션
  .gitignore
  client/src/App.tsx
  client/src/commons/constants.ts
  client/src/components/index.ts
  client/src/components/large/HotDealSection/index.tsx
  client/src/components/large/HotDealSection/style.ts
  client/src/components/medium/SectionHeader/style.ts
  client/src/components/small/HotDealBigProductCard/index.tsx
  client/src/components/small/HotDealBigProductCard/style.ts
  client/src/components/small/HotDealTimer/index.tsx
  client/src/components/small/HotDealTimer/style.ts
  client/src/libs/axios.ts
  client/src/pages/BannerPage/index.tsx
  client/src/pages/BannerPage/style.ts
  client/src/pages/MainPage/index.tsx
  client/src/pages/index.ts
  client/src/styles/globalstyle.scss
Labels: feature, 프론트엔드

#37 상품 디테일 모달
  client/src/App.tsx
  client/src/apis/index.ts
  client/src/components/index.ts
  client/src/components/large/ProductDetailModal/index.tsx
  client/src/components/large/ProductDetailModal/style.ts
  client/src/components/medium/PageHeader/index.tsx
  client/src/components/medium/PageHeader/style.ts
  client/src/components/small/Framework7Icon/index.tsx
  client/src/components/small/ProductCard/index.tsx
  client/src/components/small/SectionHeader/index.tsx
  client/src/hooks/useProducts/actions.ts
  client/src/hooks/useProducts/index.ts
  client/src/pages/ProductDetailPage/index.tsx
  client/src/pages/index.ts
  client/src/styles/globalstyle.scss
  client/src/types/data.ts
  client/src/utils/functions.ts
  server/controllers/product.js
  server/models/product.js
  server/routes/product.js
Labels: feature, 프론트엔드

#45 상품 디테일 페이지, 장바구니 Badge 기능
  client/public/assets/cart.png
  client/src/App.tsx
  client/src/commons/constants.ts
  client/src/components/index.ts
  client/src/components/large/ProductDetailModal/index.tsx
  client/src/components/large/ProductDetailModal/style.ts
  client/src/components/medium/AddCartModal/index.tsx
  client/src/components/medium/AddCartModal/style.ts
  client/src/components/medium/ProductSortModal/index.tsx
  client/src/components/small/CartBadge/index.tsx
  client/src/components/small/CartBadge/style.ts
  client/src/components/small/ProductCard/index.tsx
  client/src/components/small/QuantityCoutner/index.tsx
  client/src/components/small/QuantityCoutner/style.ts
  client/src/contexts/user/index.tsx
  client/src/libs/axios.ts
  client/src/pages/MainPage/index.tsx
  client/src/pages/ProductDetailPage/index.tsx
  client/src/pages/UserPage/index.tsx
  client/src/styles/globalstyle.scss
  client/src/utils/functions.ts
  client/src/utils/storage.ts
Labels: bug, feature, 프론트엔드

#53 Search Page 및 기능 구현(검색 기록 저장 및 검색 결과)
  client/public/assets/category-more.png
  client/public/assets/sad.png
  client/src/App.tsx
  client/src/apis/category.ts
  client/src/apis/category.tsx
  client/src/apis/user.ts
  client/src/commons/constants.ts
  client/src/components/index.ts
  client/src/components/large/CategoryProductSection/index.tsx
  client/src/components/large/ProductSection/index.tsx
  client/src/components/large/RecentSearchSection/index.tsx
  client/src/components/large/RecentSearchSection/style.ts
  client/src/components/medium/CategoryIconGrid/index.tsx
  client/src/components/medium/CategoryProductHeader/index.tsx
  client/src/components/medium/PageHeader/index.tsx
  client/src/components/medium/PageHeader/style.ts
  client/src/components/medium/RecentSearchHeader/index.tsx
  client/src/components/medium/RecentSearchHeader/style.ts
  client/src/components/medium/RecentSearchListView/index.tsx
  client/src/components/medium/RecentSearchListView/style.ts
  client/src/components/medium/SearchBar/index.tsx
  client/src/components/medium/SearchBar/style.ts
  client/src/components/medium/SubcategoryCardGrid/index.tsx
  client/src/components/medium/SubcategoryCardGrid/style.ts
  client/src/hooks/useProducts/actions.ts
  client/src/pages/CategoryPage/index.tsx
  client/src/pages/CategoryPage/style.ts
  client/src/pages/MainPage/index.tsx
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/style.ts
  client/src/pages/SearchResultPage/index.tsx
  client/src/pages/SearchResultPage/style.ts
  client/src/pages/SubcategoryPage/index.tsx
  client/src/pages/index.ts
  client/src/types/data.ts
  client/src/utils/storage.ts
  server/controllers/product.js
  server/controllers/subcategory.js
  server/models/product.js
Labels: feature, 프론트엔드

#55 배너 무한 스크롤 구현 및 사파리 scrollTo smooth 옵션 미작동 해결
  client/package.json
  client/src/commons/constants.ts
  client/src/components/medium/BannerSlider/index.tsx
  client/src/components/medium/BannerSlider/style.ts
  client/src/components/small/BannerIndicator/style.ts
  client/src/index.tsx
  client/yarn.lock
Labels: bug, feature, 프론트엔드

#59 Optional JWT Middleware (hasJwtToken) 구현
  server/middlewares/auth.js
  server/routes/product.js
Labels: feature, 백엔드

#65 찜 기능 구현 및 컴포넌트화
  client/src/apis/index.ts
  client/src/apis/product.ts
  client/src/commons/svgs.tsx
  client/src/components/index.ts
  client/src/components/large/CategoryProductSection/index.tsx
  client/src/components/large/ProductSection/index.tsx
  client/src/components/medium/ProductCardGrid/index.tsx
  client/src/components/medium/ProductCardListView/index.tsx
  client/src/components/small/ProductCard/index.tsx
  client/src/components/small/ProductCard/style.ts
  client/src/components/small/ProductLikeIcon/index.tsx
  client/src/contexts/user/actions.ts
  client/src/hooks/useProducts/actions.ts
  client/src/hooks/useProducts/index.ts
  client/src/hooks/useProducts/reducer.ts
  client/src/pages/CategoryPage/index.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/ProductDetailPage/index.tsx
  client/src/pages/SearchResultPage/index.tsx
  client/src/pages/SearchResultPage/style.ts
  client/src/pages/SubcategoryPage/index.tsx
  client/src/pages/UserPage/index.tsx
  client/src/types/data.ts
  client/src/types/states.ts
  server/controllers/product.js
  server/controllers/user.js
  server/lib/passport.js
  server/middlewares/validator.js
  server/models/product.js
  server/models/subcategory.js
  server/routes/user.js
Labels: feature, 백엔드, 프론트엔드

#63 장바구니 페이지
  client/public/assets/cart-empty.png
  client/src/App.tsx
  client/src/apis/index.ts
  client/src/apis/order.ts
  client/src/components/index.ts
  client/src/components/large/CartSection/aseets/checkbox-active.png
  client/src/components/large/CartSection/aseets/checkbox-default.png
  client/src/components/large/CartSection/index.tsx
  client/src/components/large/CartSection/style.ts
  client/src/components/medium/AddCartModal/index.tsx
  client/src/components/medium/AddCartModal/style.ts
  client/src/components/small/CartBadge/index.tsx
  client/src/components/small/CartDeleteModal/index.tsx
  client/src/components/small/CartDeleteModal/style.ts
  client/src/components/small/CartItem/index.tsx
  client/src/components/small/CartItem/style.ts
  client/src/components/small/Empty/index.tsx
  client/src/components/small/Empty/style.ts
  client/src/components/small/TotalCartMoney/index.tsx
  client/src/components/small/TotalCartMoney/style.ts
  client/src/pages/CartPage/index.tsx
  client/src/pages/ProductDetailPage/index.tsx
  client/src/pages/index.ts
  client/src/styles/globalstyle.scss
  client/src/types/data.ts
  client/src/utils/storage.ts
  server/app.js
  server/bin/www
Labels: feature, 프론트엔드

#67 order 생성 API 함수 추가 구현
  client/src/apis/order.ts
  client/src/components/large/CartSection/index.tsx
  server/controllers/order.js
  server/middlewares/validator.js
  server/routes/order.js
Labels: feature, 백엔드

#68 메뉴(햄버거바) 페이지 구현
  client/src/App.tsx
  client/src/components/index.ts
  client/src/components/large/MenuUserSection/index.tsx
  client/src/components/large/MenuUserSection/style.ts
  client/src/components/medium/MenuListGrid/index.tsx
  client/src/components/medium/MenuListGrid/style.ts
  client/src/components/medium/MenuListGridHeader/index.tsx
  client/src/components/medium/MenuListGridHeader/style.ts
  client/src/components/medium/PageHeader/index.tsx
  client/src/components/medium/SinglePageHeader/index.tsx
  client/src/components/small/BackButton/index.tsx
  client/src/pages/MenuPage/index.tsx
  client/src/pages/MenuPage/style.ts
  client/src/pages/index.ts
  client/src/types/data.ts
Labels: feature, 프론트엔드

#70 HomePage 카테고리별 대표상품 헤더 애니메이션 구현 및 API 연결
  client/src/components/large/CategoryProductSection/index.tsx
  client/src/components/large/ProductSection/index.tsx
  client/src/components/medium/CategoryProductHeader/index.tsx
  client/src/components/medium/CategoryProductHeader/style.ts
  client/src/components/medium/ProductCardGrid/index.tsx
  client/src/components/medium/ProductCardListView/index.tsx
  client/src/components/small/ProductCard/index.tsx
  client/src/pages/MainPage/index.tsx
  server/models/subcategory.js
Labels: feature, 백엔드, 프론트엔드

#72 찜한 상품 목록 및 type별 product list AP 구현
  client/src/pages/MainPage/index.tsx
  client/src/types/data.ts
  server/controllers/product.js
  server/models/product.js
Labels: feature, 백엔드

#69 온보딩 페이지 Design 리팩토링, 로그인시 Redirect 기능 추가
  client/src/App.tsx
  client/src/apis/index.ts
  client/src/apis/user.ts
  client/src/commons/constants.ts
  client/src/commons/svgs.tsx
  client/src/components/index.ts
  client/src/components/large/CartSection/index.tsx
  client/src/components/large/JoinSection/index.tsx
  client/src/components/large/JoinSection/style.ts
  client/src/components/large/LoginSection/index.tsx
  client/src/components/large/LoginSection/style.ts
  client/src/components/small/UserFooter/index.tsx
  client/src/components/small/UserFooter/style.ts
  client/src/components/small/UserHeader/index.tsx
  client/src/components/small/UserHeader/style.ts
  client/src/components/small/UserInput/index.tsx
  client/src/components/small/UserInput/style.ts
  client/src/contexts/user/actions.ts
  client/src/contexts/user/index.tsx
  client/src/contexts/user/reducer.ts
  client/src/hooks/useProducts/index.ts
  client/src/pages/CategoryPage/index.tsx
  client/src/pages/JoginPage/index.tsx
  client/src/pages/LoginPage/index.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/SubcategoryPage/index.tsx
  client/src/pages/UserPage/index.tsx
  client/src/pages/index.ts
  server/controllers/user.js
  server/routes/user.js
Labels: feature, 프론트엔드

#77 찜한상품 페이지 구현, 리팩토링(Axios, useProducts 필터링 옵션 상수화)
  client/src/App.tsx
  client/src/apis/category.ts
  client/src/apis/order.ts
  client/src/apis/product.ts
  client/src/apis/user.ts
  client/src/components/small/Empty/index.tsx
  client/src/components/small/Empty/style.ts
  client/src/hooks/useProducts/index.ts
  client/src/libs/axios.ts
  client/src/pages/JoinPage/index.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/UserLikedPage/index.tsx
  client/src/pages/UserLikedPage/style.ts
  client/src/pages/index.ts
Labels: feature, 프론트엔드

#81 로그인 필수 루트 구현 및 리팩토링(이전 페이지 이동)
  client/src/App.tsx
  client/src/apis/user.ts
  client/src/commons/constants.ts
  client/src/components/large/CartSection/index.tsx
  client/src/components/large/LoginSection/index.tsx
  client/src/components/medium/PageHeader/index.tsx
  client/src/components/medium/SearchBar/index.tsx
  client/src/contexts/user/index.tsx
  client/src/pages/CategoryPage/index.tsx
  client/src/pages/JoinPage/index.tsx
  client/src/pages/LoginPage/index.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/ProductDetailPage/index.tsx
  client/src/pages/SubcategoryPage/index.tsx
  client/src/pages/UserLikedPage/index.tsx
  client/src/types/data.ts
Labels: feature, 프론트엔드

#78 주문 내역 페이지 구현
  client/src/App.tsx
  client/src/apis/order.ts
  client/src/components/index.ts
  client/src/components/large/MenuUserSection/style.ts
  client/src/components/medium/OrderCardListView/index.tsx
  client/src/components/medium/OrderCardListView/style.ts
  client/src/components/medium/SinglePageHeader/index.tsx
  client/src/components/small/OrderCard/index.tsx
  client/src/components/small/OrderCard/style.ts
  client/src/pages/OrderListPage/index.tsx
  client/src/pages/OrderListPage/style.ts
  client/src/pages/SearchResultPage/style.ts
  client/src/pages/index.ts
  client/src/styles/globalstyle.scss
  client/src/types/data.ts
  client/src/utils/functions.ts
  server/controllers/order.js
  server/models/order.js
Labels: feature, 백엔드, 프론트엔드

#76 버그 픽스 #73 #74
  client/src/components/medium/SearchBar/index.tsx
  client/src/pages/MainPage/index.tsx
Labels: QA, bug, 프론트엔드

#83 로그아웃 페이지 구현
  client/src/App.tsx
  client/src/components/large/MenuUserSection/index.tsx
  client/src/pages/LoginPage/index.tsx
  client/src/pages/LogoutPage/index.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/index.ts
Labels: feature, 프론트엔드

#85 페이지 헤더 수정 및 뒤로가기 구현
  client/src/components/large/MenuUserSection/index.tsx
  client/src/components/medium/BannerSlider/index.tsx
  client/src/components/medium/CategoryIconGrid/index.tsx
  client/src/components/medium/MenuListGrid/index.tsx
  client/src/components/medium/PageHeader/index.tsx
  client/src/components/medium/PageHeader/style.ts
  client/src/components/medium/RecentSearchListView/index.tsx
  client/src/components/medium/SearchBar/index.tsx
  client/src/components/medium/SubcategoryCardGrid/index.tsx
  client/src/components/small/CartBadge/index.tsx
  client/src/components/small/ProductCard/index.tsx
  client/src/utils/functions.ts
Labels: feature, 프론트엔드

#86 HOTFIX: 유저 메뉴 섹션에 location 변수 추가
  client/src/components/large/MenuUserSection/index.tsx
Labels: bug, 프론트엔드

#94 HOTFIX: 폰트 적용 안되는 버그
  client/src/App.tsx
  client/src/pages/MainPage/index.tsx
  client/src/styles/globalstyle.scss
  client/src/styles/reset.scss
Labels: bug, 프론트엔드

#95 메타 태그, 파비콘, 타이틀 적용
  client/public/assets/favicon.ico
  client/public/assets/og-image.jpg
  client/public/index.html
Labels: 프론트엔드

#97 [동욱] TODO LIST
  client/src/components/large/ProductDetailModal/index.tsx
  client/src/components/large/ProductDetailModal/style.ts
  client/src/components/medium/AddCartModal/index.tsx
  client/src/components/medium/RecentSearchListView/index.tsx
  client/src/components/medium/SearchBar/index.tsx
  client/src/components/small/HotDealBigProductCard/index.tsx
  client/src/components/small/OrderCard/index.tsx
  client/src/components/small/ProductCard/index.tsx
  client/src/pages/SearchResultPage/index.tsx
  client/src/styles/globalstyle.scss
  client/src/styles/reactModal.scss
  client/src/utils/validation.ts
Labels: QA, bug, feature, 프론트엔드

#99 주문완료 페이지 구현,연결 및 주문내역 작업 (텅빔 상태, 로그인 필수 처리)
  client/public/assets/woowa-friends.png
  client/src/App.tsx
  client/src/components/large/CartSection/index.tsx
  client/src/components/medium/PageHeader/style.ts
  client/src/pages/OrderCompletePage/index.tsx
  client/src/pages/OrderCompletePage/style.ts
  client/src/pages/OrderListPage/index.tsx
  client/src/pages/OrderListPage/style.ts
  client/src/pages/index.ts
Labels: feature, 프론트엔드

#98 HOTFIX: CSS 이슈 해결
  client/public/assets/bmart-logo.png
  client/src/commons/svgs.tsx
  client/src/components/index.ts
  client/src/components/large/JoinSection/index.tsx
  client/src/components/large/LoginSection/index.tsx
  client/src/components/medium/CategoryProductHeader/index.tsx
  client/src/components/medium/PageHeader/index.tsx
  client/src/components/medium/ProductCardGridHeader/style.ts
  client/src/components/small/BmartLogo/index.tsx
Labels: feature, 프론트엔드

#101 스크롤 이슈 수정
  client/src/components/large/ProductDetailModal/style.ts
  client/src/components/large/ProductSection/style.ts
  client/src/components/medium/ProductCardListView/style.ts
  client/src/components/medium/ProductSortModal/index.tsx
Labels: bug

#104 장바구니 버그수정
  client/src/components/large/CartSection/index.tsx
  client/src/components/large/CartSection/style.ts
Labels: bug, 프론트엔드

#108 장바구니 배지 추가
  client/src/pages/CategoryPage/index.tsx
  client/src/pages/SubcategoryPage/index.tsx
Labels: feature, 프론트엔드

#107 기본 정렬 옵션, 배너 이미지, 핫딜 시간&링크 연결, 미사용 import 제거
  client/src/commons/constants.ts
  client/src/components/medium/CategoryProductHeader/index.tsx
  client/src/components/medium/MenuListGridHeader/index.tsx
  client/src/components/medium/MenuListGridHeader/style.ts
  client/src/components/medium/ProductSortModal/index.tsx
  client/src/components/medium/ProductSortModal/style.ts
  client/src/components/small/CartItem/index.tsx
  client/src/components/small/HotDealBigProductCard/index.tsx
  client/src/components/small/HotDealBigProductCard/style.ts
  client/src/components/small/OrderCard/index.tsx
  client/src/pages/CategoryPage/index.tsx
  client/src/pages/JoinPage/index.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/OrderCompletePage/index.tsx
  client/src/utils/functions.ts
Labels: feature, 프론트엔드

#109 반응형 이슈 리스트 부분 해결
  client/src/commons/svgs.tsx
  client/src/components/medium/CategoryProductHeader/index.tsx
  client/src/components/medium/ProductSortModal/index.tsx
  client/src/components/medium/ProductSortModal/style.ts
  client/src/styles/reset.scss
Labels: bug, 프론트엔드

#112 장바구니 피드백 반영
  client/src/components/index.ts
  client/src/components/large/CartSection/index.tsx
  client/src/components/large/CartSection/style.ts
  client/src/components/medium/CategoryIconGrid/index.tsx
  client/src/components/small/CartItem/style.ts
  client/src/components/small/Loading/index.tsx
  client/src/components/small/Slot/index.tsx
  client/src/styles/globalstyle.scss
Labels: bug, feature, 프론트엔드

#115 상세정보 가격 색상, 정렬 모달 높이, 담기버튼 포인터 적용
  client/src/components/large/ProductDetailModal/style.ts
  client/src/components/medium/ProductSortModal/index.tsx
  client/src/components/medium/ProductSortModal/style.ts
Labels: bug, 프론트엔드

#116 로그인 필수인 경우만 메세지 표시 및 Naver Analytics 추가
  client/public/index.html
  client/src/components/large/LoginSection/index.tsx
Labels: feature, 프론트엔드

#118 HOTFIX: 땡겨요 스크롤 이벤트 충돌 해결
  client/src/pages/MainPage/index.tsx
Labels: bug, 프론트엔드
